export const IMAGES_MAP = {
    '01d': 'clearSkyDay.jpg', 
    '01n': 'clearSkyNight.jpg', 
    '02d': 'fewCloudsDay.jpg', 
    '02n': 'fewCloudsNight.jpg', 
    '03d': 'scatteredCloudsDay.jpg', 
    '03n': 'scatteredCloudsNight.jpg', 
    '04d': 'brokenCloudsDay.jpg', 
    '04n': 'brokenCloudsDay.jpg', 
    '09d': 'rainDay.jpg', 
    '09n': 'rainNight.jpg', 
    '10d': 'rainDay.jpg', 
    '10n': 'rainNight.jpg', 
    '11d': 'thunderstormDay.jpg', 
    '11n': 'thunderstormNight.jpg', 
    '13d': 'snowDay.jpg', 
    '13n': 'snowNight.jpg', 
    '50d': 'mistDay.jpg', 
    '50n': 'mistNight.jpg', 
}